### ISSUE TITLE
Compile to es5 for the published version

### ISSUE THREAD

**Issue by OscarBarrett** [commenthol/date-holidays-parser#1]
When trying to use this module with webpack and uglify it fails due to es6 features.

See https://github.com/webpack/webpack/issues/5682#issuecomment-352684206

Ideally there should be a prepublish script to compile the code to es5 so that it can be used with webpack without having to be specifically targeted for compilation.

I'd be happy to do up a PR for this if you want.

**Comment by commenthol** [comment]
Hi, there is an ES5 version provided in the module.

Please use in your webpack config:

```
resolve: {
  mainFields: ["browser", "main", "module"]
}
```

please take a look here:
<https://webpack.js.org/configuration/resolve/#resolve-mainfields>

**Comment by OscarBarrett** [comment]
Ah cool, thanks! So if I understand correctly, webpack by default follows `module` before `main` which in this case results in the source being used instead of the transpiled version in `lib`.

It might be worth mentioning this config in the main repo as it seems like others have also run into this from the linked thread.
