### ISSUE TITLE
Custom holiday list

### ISSUE THREAD

**Issue by misomighty** [commenthol/date-holidays-parser#29]
My company's business logic requires me to filter for only major holidays and a few local city holidays.
I've tried filtering the array from hd.getHolidays() and then setting the new filtered array of holidays but i'm still getting all of the holidays. 

Is there a way to overwrite the current holiday array?

**Comment by commenthol** [comment]
You are free to create your own list of rules for your required holidays. 
An example is provided in `test/Holidays.mocha.js` using `test/fixtures/custom.json`.
