### ISSUE TITLE
Get holidays for a subset (or all) the available countries

### ISSUE THREAD

**Issue by jmezzeragp** [commenthol/date-holidays-parser#34]
Hi.
First of all, thanks for this work, is amazing!

As part of discovering holidays data sources, I found this project. One of my uses cases would be to query all the holidays for a list of countries. Looking at the API docs, I found that the init method receives a Country instance. Is there a way to extend this to receive a list of countries? I guess one approach could be having a list of Holidays instances but a) Not sure how this would perform and 2) It would be cleaner to leave that to the module instead.

Any guidance on this would be appreciated.

**Comment by commenthol** [comment]
Please find info on usage at https://github.com/commenthol/date-holidays-parser#usage
and a related example at https://github.com/commenthol/date-holidays/blob/master/examples/readme.js
