### ISSUE TITLE
Must use import to load ES Module

### ISSUE THREAD

**Issue by diegobmss** [commenthol/date-holidays-parser#35]
Hello,

I'm using date-holidays in a Vtex.IO project.

Here I can only use import and not require.

However, I am getting this error when trying to use the lib.

![Captura de Tela 2021-08-11 às 11 57 13](https://user-images.githubusercontent.com/7568931/129053380-50eaa565-9be9-4d4e-af89-04ed516a4e9f.png)

Any way to solve?

**Comment by commenthol** [comment]
Hi @diegobmss,
Did you found a solution to your problem? In case there is one please post you findings.
