### ISSUE TITLE
Including in Angular causing commonjs warnings

### ISSUE THREAD

**Issue by Gillardo** [commenthol/date-holidays-parser#49]
Can the project be updated to support Es2020, or at least ES2015 so packaging of the code can take advantage of tree shaking.

You get warning like this atm

![image](https://user-images.githubusercontent.com/7406381/184510550-f677c452-342d-49d8-95dc-febce85129ff.png)

My tsconfig file looks like so

```
{
  "extends": "../../tsconfig.json",
  "compilerOptions": {
    "baseUrl": "./",
    "outDir": "../../out-tsc/app",
    "types": [],
    "module": "esnext",
  },
  "files": [
    "src/main.ts",
    "src/polyfills.ts"
  ],
  "include": [
    "src/**/*.d.ts"
  ]
}
```

My route tsconfig looks like so

```
{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./",
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "downlevelIteration": true,
    "experimentalDecorators": true,
    "moduleResolution": "node",
    "importHelpers": true,
    "target": "es2020",
    "module": "es2020",
    "lib": [
      "es2018",
      "dom"
    ]
  }
}
```

**Comment by commenthol** [comment]
Hi @Gillardo,
the project uses ES2020 at ist core. Additional CJS is offered via rollup. So both options are provided via package.json exports. 
As I am not into Angular, I urge you to check your config first. If you then think that this project does requires changes, please file a PR.
