### ISSUE TITLE
Data?

### ISSUE THREAD

**Issue by fallenartist** [commenthol/date-holidays-parser#7]
I'm getting 404 on the link to holiday [data](https://github.com/commenthol/date-holidays-parser/blob/master/data/holidays.json). Is there any existing database?

**Comment by commenthol** [comment]
nope. The json file was removed from git. Its now only in the npm package. May I ask why you solely use the json file? Can you use this without a parser? Or is there a project which relies on that file?

**Comment by commenthol** [comment]
Maybe this is the project you are looking for https://github.com/commenthol/date-holidays

**Comment by fallenartist** [comment]
Yes, thanks!
