### ISSUE TITLE
set Day Off

### ISSUE THREAD

**Issue by Fancap** [commenthol/date-holidays-parser#8]
Hi there,

hd.getDayOff() returns undefined (country 'CH', 'GE'))

setDayOff() does not exist, and can't find any documentation related. Can you help me ? 

Thanks

**Comment by commenthol** [comment]
the tag "dayoff" is missing in CH.yaml  - sorry for that
Documentation is here: https://github.com/commenthol/date-holidays/blob/master/docs/specification.md#structure-of-holidaysyaml
```
    dayoff: {String}    # name of weekday which is a default day off (friday|saturday|sunday|...)
```

**Comment by Fancap** [comment]
thanks! found a workaround :)
